@startuml
start
:Прийти на кухню;
:Взять яйца в холодильнике;
:Отмыть яйца от загрязнений;
if (сковородка немытая?) then (Да)
    :Помыть сковородку;
else (Нет)
endif
:налить подсолнечное масло на сковородку;
:нарезать и положить колбасу на сковородку;
:включить плиту на малую мощность;
:Вести наблюдение;
if (Колбаса не обжарилась?) then (Да)
    :подождать завершение обжарки колбасы;
else (Нет)
endif
:Поместить содержимое яиц на сковородку;
:Посолить;
:Поcыпать сверху сухариками;
:Вести наблюдение за готовкой;
if (Яишница не готова?) then (Да)
    :подождать завершение готовки яишницы;
else (Нет)
endif
:Отключить плиту;
:Разложить яишницу порциями на тарелки;
:Подать на стол;
stop
@enduml



